apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: springboot
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30005