apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: fenleap-testdb
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fenleap-testdb
