apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi  # Storage capacity of the PersistentVolume
  accessModes:
    - ReadWriteMany # Access mode
  hostPath:
    path: /data/postgresql  # Host path  where the PersistentVolume is created
